#!/usr/bin/env python3
"""Recover in-memory definition layouts from the original's loaders.

Each definition type (unit, unit state, weapon, player, level) is read
by one function that calls U_Token_Get<Type>(text, &cursor, "#key TYPE",
&base[offset]) once per key. Scraping those calls from the Ghidra corpus gives
a table of key -> type -> byte offset, which is how decompiled gameplay code
reading `*(float *)(def + 0x268)` is mapped back to a named field.

Ghidra truncates string labels (s__doNotSpawnIfTypeAlreadyExists_B_004f6d4d),
so the full key is read from the executable at the label's address.

Usage: layout.py <exe> <export-dir> <out-dir> [--odin <file.odin>]
Writes <out-dir>/<loader>.tsv (offset, type, key), and with --odin the typed
definition structs the simulation uses, each field tagged with its original
key (for the loader in data/) and commented with its original offset (for
reading the decompilation).
"""
import re
import struct
import sys
from pathlib import Path

LOADERS = {
    "unitdef": "G_UnitDef/FUN_004422a0.c",
    "unitdef_state": "G_UnitDef/FUN_004431f0.c",
    "wepdef": "G_WepDef/FUN_00445cf0.c",
    "playerdef": "G_PlayerDef/FUN_004368a0.c",
    "level": "G_Level/FUN_00429b70.c",
}

CALL = re.compile(r"U_Token_Get(\w+)\s*\((.*?)\)\s*;")
# Offsets are sometimes passed through a pointer variable:
#     plVar2 = (long *)(iVar1 + 0x9c2);  ...  U_Token_GetID(..., plVar2);
ALIAS = re.compile(r"(\w+)\s*=\s*\([\w ]+\*\)\s*\(\s*(\w+)\s*\+\s*(0x[0-9a-f]+|\d+)\s*\)\s*;")
LABEL = re.compile(r"\b(?:s|DAT)_\w*?_?([0-9a-f]{8})\b")
OFFSET = re.compile(r"\(\s*(\w+)\s*\+\s*(0x[0-9a-f]+|\d+)\s*\)\s*(?:,|$)")


class PE:
    def __init__(self, path):
        self.b = Path(path).read_bytes()
        pe = struct.unpack_from("<I", self.b, 0x3C)[0]
        nsec = struct.unpack_from("<H", self.b, pe + 6)[0]
        opt = struct.unpack_from("<H", self.b, pe + 20)[0]
        self.base = struct.unpack_from("<I", self.b, pe + 24 + 28)[0]
        self.secs = []
        o = pe + 24 + opt
        for _ in range(nsec):
            vsize, va, rsize, raw = struct.unpack_from("<IIII", self.b, o + 8)
            self.secs.append((self.base + va, max(vsize, rsize), raw))
            o += 40

    def cstr(self, va):
        for start, size, raw in self.secs:
            if start <= va < start + size:
                off = raw + va - start
                end = self.b.index(b"\0", off)
                return self.b[off:end].decode("latin-1")
        return None


# Odin struct per layout. `base` is subtracted from offsets for display so a
# state field reads as the offset within one state record, and `strip` drops
# a prefix every key in the struct shares.
# `bases` selects rows by the loader's base pointer. State offsets stay
# relative to the unit definition (def + state * 0x5da + off), which is how
# the decompiled gameplay code addresses them.
STRUCTS = [
    ("Unit_Def", "unitdef", None, ""),
    ("State_Def", "unitdef_state", {"iVar1"}, "state"),
    ("Spawn_Set_Def", "unitdef_state", {"pGVar8"}, "stateSpawnSet"),
    ("Wep_Def", "wepdef", {"param_3"}, ""),
    ("Wep_Spawn_Def", "wepdef", {"pcVar2"}, "spawn"),
    ("Player_Def", "playerdef", None, ""),
]
TYPES = {"Int": "i32", "Float": "f32", "Boolean": "bool", "ID": "Res_ID",
         "Color": "Color", "String": "string", "Rect": "Rect"}
SUFFIX = re.compile(r"_(INT|FLOAT|BOOL|ID|COLOR|STR|RECT)$")


def snake(key, strip):
    k = SUFFIX.sub("", key.lstrip("#"))
    if strip and k.startswith(strip) and len(k) > len(strip) and not k[len(strip)].islower():
        k = k[len(strip):]
    k = re.sub(r"[^A-Za-z0-9 _]+", "", k)  # stateSpawnSetDon'tSpawnOffscreen
    k = k.replace("_", " ")
    k = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", k)
    k = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", k)
    return "_".join(k.lower().split())


def odin(out_dir, path):
    lines = [
        "// Generated by tools/decomp/layout.py from symbols/layouts/. Do not edit;",
        "// run `mise run decomp:layout`.",
        "//",
        "// Each field is one key read by the original's definition loader. The tag",
        "// is that key, so data/ can fill the struct from our JSON records; the",
        "// comment is the byte offset in the original's in-memory struct, so",
        "// `*(float *)(def + 0x268)` in the decompilation can be found here.",
        "// Field order follows the original layout.",
        "package sim",
        "",
    ]
    for name, table, bases, strip in STRUCTS:
        rows = [l.split("\t") for l in (Path(out_dir) / f"{table}.tsv").read_text().splitlines()[1:]]
        seen = {}
        fields = []
        for off, kind, key, b in rows:
            if bases is not None and b not in bases:
                continue
            f = snake(key, strip)
            if f in seen:
                f = f"{f}_{int(off, 0):x}"
            seen[f] = True
            fields.append((f, TYPES[kind], key.lstrip("#"), int(off, 0)))
        w = max(len(f) for f, *_ in fields) + 1
        tw = max(len(t) for _, t, *_ in fields)
        kw = max(len(k) for *_, k, _ in fields) + len('`dr:""`,')
        lines.append(f"{name} :: struct {{")
        for f, t, k, off in fields:
            tag = f'`dr:"{k}"`,'
            lines.append(f"\t{(f + ':').ljust(w)} {t.ljust(tw)} {tag.ljust(kw)} // +{off:#05x}")
        lines += ["}", ""]
    Path(path).write_text("\n".join(lines))


def main():
    if "--odin" in sys.argv:
        i = sys.argv.index("--odin")
        odin_out = sys.argv[i + 1]
        del sys.argv[i : i + 2]
    else:
        odin_out = None
    exe, export, out = sys.argv[1:4]
    pe = PE(exe)
    Path(out).mkdir(parents=True, exist_ok=True)
    for name, rel in LOADERS.items():
        # Ghidra wraps long calls, sometimes putting the ';' on its own line.
        src = " ".join((Path(export) / rel).read_text().split())
        rows, missed = [], []
        alias = {}
        pos = 0
        for m in CALL.finditer(src):
            # Aliases assigned before this call (last assignment wins).
            for a in ALIAS.finditer(src, pos, m.start()):
                alias[a.group(1)] = (int(a.group(3), 0), a.group(2))
            pos = m.start()
            kind, args = m.group(1), m.group(2)
            lab = LABEL.search(args)
            if not lab:
                continue
            key = pe.cstr(int(lab.group(1), 16))
            if key is None:
                continue
            off = OFFSET.search(args)
            last = args.rsplit(",", 1)[-1].strip()
            if off:
                rows.append((int(off.group(2), 0), kind, key.strip(), off.group(1)))
            elif last in alias:
                rows.append((alias[last][0], kind, key.strip(), alias[last][1]))
            else:
                missed.append(key.strip())
        rows.sort()
        with open(Path(out) / f"{name}.tsv", "w") as f:
            # base: the loader's pointer the offset is relative to. In the
            # state loader, iVar1 = def + state * 0x5da and pGVar8 is a
            # separately allocated spawn-set record.
            f.write("offset\ttype\tkey\tbase\n")
            for o, k, key, b in rows:
                f.write(f"{o:#06x}\t{k}\t{key}\t{b}\n")
        print(f"{name}: {len(rows)} keys" + (f"; unresolved: {missed}" if missed else ""))
    if odin_out:
        odin(out, odin_out)
        print(f"wrote {odin_out}")


if __name__ == "__main__":
    main()
