#!/usr/bin/env python3
"""Generate sim/math_tables.odin: the U_Math lookup tables, bit for bit.

U_Math_Init (0x402170) builds them at startup:
    atan[i] = (int)(atan(i * 0.01) * 57.2957795)       i < 1024
    cos[i]  = cosf((float)i * 0.0174532924f)           i < 360
    sin[i]  = sinf((float)i * 0.0174532924f)
These formulas, evaluated with correctly rounded maths, reproduce the tables
dumped from the running original (`mise run oracle:tables`) exactly: 0 of
360 + 360 + 1024 entries differ. Emitting bit patterns keeps the simulation
independent of the host libm.
"""
import math
import struct
import sys

f32 = lambda x: struct.unpack("<f", struct.pack("<f", x))[0]
bits = lambda x: struct.unpack("<I", struct.pack("<f", x))[0]
DEG = f32(0.01745329238474369)  # 0x4d8650


def rows(vals, fmt, per=8):
    out = []
    for i in range(0, len(vals), per):
        out.append("\t" + " ".join(fmt(v) + "," for v in vals[i : i + per]))
    return "\n".join(out)


def main():
    sin = [bits(f32(math.sin(f32(i * DEG)))) for i in range(360)]
    cos = [bits(f32(math.cos(f32(i * DEG)))) for i in range(360)]
    atan = [int(math.atan(i * 0.01) * 57.2957795) for i in range(1024)]
    src = f"""// Generated by tools/decomp/math_tables.py. Do not edit.
//
// The original's U_Math lookup tables, as f32 bit patterns so they are exact
// on any host. Verified against memory dumped from the running original.
package sim

@(rodata)
SIN_BITS := [360]u32{{
{rows(sin, lambda v: f"0x{v:08x}")}
}}

@(rodata)
COS_BITS := [360]u32{{
{rows(cos, lambda v: f"0x{v:08x}")}
}}

// Degrees, indexed by (tangent * 100).
@(rodata)
ATAN_DEG := [1024]i32{{
{rows(atan, lambda v: f"{v:2d}", 16)}
}}
"""
    open(sys.argv[1], "w").write(src)


if __name__ == "__main__":
    main()
