FROM docker.io/library/debian:bookworm-slim
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        wine wine32:i386 wine64 xvfb xauth x11-apps imagemagick \
        cabextract p7zip-full file ca-certificates && \
    rm -rf /var/lib/apt/lists/*
ENV WINEDEBUG=-all
ENV WINEDLLOVERRIDES=mscoree=d;mshtml=d
