#!/usr/bin/env bash
# Reproducibly extract "Install Deimos Rising.exe" into game/.
#
# The installer is NSIS 2.0b1 (Feb 2003). That beta's archive layout is not
# understood by 7-Zip's Nsis handler (any version tested, incl. 26.02) -- it
# uses a single solid stream whose header has no parseable block chain, so
# `7z x` fails with "Cannot open the file as [Nsis] archive".
#
# The reliable route is to run the installer's own silent mode under Wine,
# inside a throwaway network-isolated container.
#
# Usage: tools/extract_installer.sh [installer] [destdir]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-$ROOT/orig/Install Deimos Rising.exe}"
DEST="${2:-$ROOT/game}"
IMAGE=deimos-wine
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

[ -f "$SRC" ] || { echo "installer not found: $SRC" >&2; exit 1; }

if ! podman image exists "$IMAGE"; then
    echo ">> building $IMAGE"
    podman build -t "$IMAGE" -f "$ROOT/tools/Containerfile" "$ROOT/tools"
fi

cp "$SRC" "$WORK/installer.exe"

echo ">> running silent install under Wine (no network)"
podman run --rm --network=none \
    -v "$WORK:/work:z" \
    -e WINEPREFIX=/work/prefix -e HOME=/work \
    "$IMAGE" bash -c '
        set -e
        wineboot -i >/dev/null 2>&1
        cd /work
        xvfb-run -a wine installer.exe /S "/D=C:\out"
    '

OUT="$WORK/prefix/drive_c/out"
[ -d "$OUT" ] || { echo "install produced no output" >&2; exit 1; }

# Uninstall.exe is generated by NSIS at install time, not shipped payload.
rm -f "$OUT/Uninstall.exe"

mkdir -p "$DEST"
cp -a "$OUT/." "$DEST/"
echo ">> extracted $(find "$DEST" -type f | wc -l) files to $DEST"
